server:
  port: 8761

spring:
  application:
    name: eureka-server
  # Security-г бүрэн унтраах
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0